### Login (Before Oauth Form)
POST http://127.0.0.1:8000/login HTTP/1.1
content-type: application/json

{
    "email": "duentes5@gmail.com",
    "password": "Password!"
}

### ERROR Login
POST http://127.0.0.1:8000/login HTTP/1.1
content-type: application/json

{
    "email": "duentes5@gmail.com",
    "password": "Password"
}



### Login Formulario

POST http://127.0.0.1:8000/login
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="username"

duentes5@gmail.com
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

Password!
----WebKitFormBoundary7MA4YWxkTrZu0gW