GET http://127.0.0.1:8000/posts HTTP/1.1


### 
GET http://127.0.0.1:8000/posts/3 HTTP/1.1


###
GET http://127.0.0.1:8000/posts/latest HTTP/1.1


###
POST http://127.0.0.1:8000/posts HTTP/1.1
content-type: application/json
Authorization: Bearer

{
    "title": "Happy Coding!",
    "content": "Never stop learning!"
}

###
DELETE http://127.0.0.1:8000/posts/4 HTTP/1.1


### 
PUT http://127.0.0.1:8000/posts/7 HTTP/1.1
content-type: application/json

{
    "title": "title updated",
    "content": "content updated"
}

###

GET http://127.0.0.1:8000/sqlalchemy HTTP/1.1